- id: '1683067517663'
  alias: 'Last Motion Log: Living Room'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.living_room_motion
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data:
      retain: true
      topic: logs/last_motion/living_room
      qos: '0'
      payload_template: '{{ as_timestamp(states.binary_sensor.living_room_motion.last_updated)
        | timestamp_custom("%b %d %I:%M %p") }}'
  mode: single
- id: '1683068274050'
  alias: 'Last Motion Log: Office'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.office_motion
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data:
      retain: true
      topic: logs/last_motion/office
      qos: '0'
      payload_template: '{{ as_timestamp(states.binary_sensor.office_motion.last_updated)
        | timestamp_custom("%b %d %I:%M %p") }}'
  mode: single
- id: '1683068377123'
  alias: 'Last Motion Log: Bedroom'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bedroom_motion
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data:
      retain: true
      topic: logs/last_motion/bedroom
      qos: '0'
      payload_template: '{{ as_timestamp(states.binary_sensor.bedroom_motion.last_updated)
        | timestamp_custom("%b %d %I:%M %p") }}'
  mode: single
- id: '1683068426747'
  alias: 'Last Opened Log: Front Door'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.front_door
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data:
      retain: true
      topic: logs/last_opened/front_door
      qos: '0'
      payload_template: '{{ as_timestamp(states.binary_sensor.front_door.last_updated)
        | timestamp_custom("%b %d %I:%M %p") }}'
  mode: single
