#------------------------------------------------------------------------------
# HOME ASSISTANT
#------------------------------------------------------------------------------
homeassistant:

  # Name of the location where Home Assistant is running
  name: Home
  external_url: !secret homeassistant_external_url
  internal_url: !secret homeassistant_internal_url

  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0

  # metric for Metric, imperial for Imperial
  unit_system: imperial

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret homeassistant_time_zone

  # Customization file
  customize: !include customize.yaml

  auth_providers:
   - type: homeassistant

#------------------------------------------------------------------------------
# FRONTEND
#------------------------------------------------------------------------------
frontend:
  themes: !include_dir_merge_named themes

#------------------------------------------------------------------------------
# CONFIG
#------------------------------------------------------------------------------
config:

#------------------------------------------------------------------------------
# HTTP
#------------------------------------------------------------------------------
http:
  use_x_forwarded_for: true
  trusted_proxies:

    # core
    - 192.168.1.222

    # allow all networks
    - 0.0.0.0/0

#------------------------------------------------------------------------------
# SYSTEM HEALTH
#------------------------------------------------------------------------------
system_health:

#------------------------------------------------------------------------------
# API
#------------------------------------------------------------------------------
api:

#------------------------------------------------------------------------------
# TTS
#------------------------------------------------------------------------------
tts:
  - platform: google_translate
    language: en
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

#------------------------------------------------------------------------------
# CONVERSATION
#------------------------------------------------------------------------------
conversation:

#------------------------------------------------------------------------------
# HISTORY
#------------------------------------------------------------------------------
history:

#------------------------------------------------------------------------------
# LOGBOOK
#------------------------------------------------------------------------------
logbook:

#------------------------------------------------------------------------------
# MAP
#------------------------------------------------------------------------------
map:

#------------------------------------------------------------------------------
# SUN
#------------------------------------------------------------------------------
sun:

#------------------------------------------------------------------------------
# InfluxDB
#------------------------------------------------------------------------------

influxdb:
  api_version: 2
  host: !secret influxdb_host
  port: !secret influxdb_port
  ssl: false
  token: !secret influxdb_token
  organization: !secret influxdb_organization
  bucket: !secret influxdb_bucket
  default_measurement: units
  tags_attributes:
    - friendly_name
  tags:
    source: HA

#------------------------------------------------------------------------------
# Node-RED
#------------------------------------------------------------------------------
panel_iframe:
 nodered:
   title: 'Node-Red'
   icon: 'mdi:shuffle-variant'
   url: 'http://192.168.1.222:1880/'

#------------------------------------------------------------------------------
# Recorder
#------------------------------------------------------------------------------
recorder:
  db_url: !secret db_url
  auto_purge: false

#------------------------------------------------------------------------------
# Includes
#------------------------------------------------------------------------------
#apple_tv: !include apple_tv.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
device_tracker: !include trackers.yaml
#glances: !include glances.yaml
group: !include groups.yaml
homekit: !include homekit.yaml
ios:
#light: !include lights.yaml
media_player: !include media_players.yaml
mobile_app:
mqtt: !include mqtt.yaml
#owntracks: !include owntracks.yaml
plant: !include plants.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
#speedtestdotnet: !include speedtest.yaml
stream:
switch: !include switches.yaml
zone: !include zones.yaml
