
#------------------------------------------------------------------------------
# Home
#------------------------------------------------------------------------------
title: Home
views:
  - title: Home
    icon: mdi:home
    cards:
      - type: entities
        title: Subway
        show_header_toggle: true
        entities:
          - sensor.mta_subway_4
          - sensor.mta_subway_5
          - sensor.mta_subway_6
          - sensor.mta_subway_q
      - type: entities
        title: Mood Lights
        show_header_toggle: true
        entities:
          - switch.bookcase
          - switch.lava_lamp
          - switch.lite_brite
          - switch.star_light
          - switch.star_bright
          - light.hoplite
          - light.blue_jar
          - light.vines
      - type: entities
        title: Testing
        show_header_toggle: true
        entities:
          - light.neopixel
          - switch.candle_2
      - type: entities
        title: Living Room
        show_header_toggle: true
        entities:
          - sensor.front_door
          - switch.petcube
          - switch.living_room_tv
          - switch.ac_main
          - switch.christmas_tree
      - type: entities
        title: Bedroom
        show_header_toggle: true
        entities:
          - switch.dohm
          - switch.blacksmith
          - switch.headboard
      - type: entities
        title: Office
        show_header_toggle: true
        entities:
          - switch.soldering_iron
      - type: entities
        title: Kitchen
        show_header_toggle: true
        entities:
          - switch.kitchen_grow_light
      - type: entities
        title: Weather
        show_header_toggle: true
        entities:
          - sun.sun
          - sensor.dark_sky_icon
          - sensor.dark_sky_nearest_storm_distance
          - sensor.dark_sky_summary
          - sensor.yr_symbol

#------------------------------------------------------------------------------
# Plants
#------------------------------------------------------------------------------
  - title: Plants
    icon: mdi:flower
    cards:
      - type: plant-status
        entity: plant.christmas_cactus
      - type: plant-status
        entity: plant.snake_plant
      - type: plant-status
        entity: plant.golden_pothos
      - type: plant-status
        entity: plant.african_violet

#------------------------------------------------------------------------------
# Media
#------------------------------------------------------------------------------
  - title: Trackers
    icon: mdi:television
    cards:
      - type: media-control
        entity: media_player.receiver
      - type: media-control
        entity: media_player.apple_tv
      - type: media-control
        entity: media_player.living_room
#------------------------------------------------------------------------------
# Trackers
#------------------------------------------------------------------------------
  - title: Trackers
    icon: mdi:radar
    cards:
      - type: entities
        entities:
          - device_tracker.maggies_iphone_8
          - device_tracker.mickeys_iphone_x
          - device_tracker.google_maps_101608876393904256312
          - device_tracker.mosquitto_mickeyowntracks
          - sensor.maggie_iphone_overall_presence
          - sensor.mickey_iphone_overall_presence
          - sensor.mickey_iphone_viacom_presence
          - sensor.bedroom_motion
          - sensor.living_room_motion
          - sensor.office_motion
